# Generated by Django 4.2.3 on 2025-01-12 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesos',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AddField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(17, 20, 5, 322553), editable=False),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(17, 20, 5, 323553), editable=False),
        ),
        migrations.AlterField(
            model_name='jornadaportrato',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(17, 20, 5, 325511), editable=False),
        ),
    ]
