# Generated by Django 4.2.3 on 2024-10-05 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0002_humiditysoil_temperaturehumiditylocation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectorpoligon',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='jornada',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(18, 27, 2, 295123), editable=False),
        ),
        migrations.AlterField(
            model_name='jornadaportrato',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(18, 27, 2, 296123), editable=False),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(18, 27, 2, 293122), editable=False),
        ),
    ]
