# Generated by Django 4.2.3 on 2025-01-12 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0003_alter_jornada_hora_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesos',
            name='fecha_compra',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(20, 33, 13, 40323), editable=False),
        ),
        migrations.AlterField(
            model_name='jornadaportrato',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(20, 33, 13, 42323), editable=False),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(20, 33, 13, 38323), editable=False),
        ),
    ]
