# Generated by Django 4.2.3 on 2024-09-25 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0003_jornadaportrato_observacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='es_jornada_por_trato',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(18, 8, 19, 784783), editable=False),
        ),
        migrations.AlterField(
            model_name='jornadaportrato',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(18, 8, 19, 785780), editable=False),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(18, 8, 19, 783786), editable=False),
        ),
    ]
