# Generated by Django 4.2.3 on 2024-11-23 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0004_humiditytemperaturasoil_sensorsuelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humiditytemperaturasoil',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperaturehumiditylocation',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(21, 46, 16, 682751), editable=False),
        ),
        migrations.AlterField(
            model_name='jornadaportrato',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(21, 46, 16, 684750), editable=False),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(21, 46, 16, 681749), editable=False),
        ),
    ]
