# Generated by Django 4.2.3 on 2024-09-25 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0004_jornada_es_jornada_por_trato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornada',
            name='detalle_gasto_total_tareas',
        ),
        migrations.RemoveField(
            model_name='jornada',
            name='detalle_gastos_total_extras',
        ),
        migrations.RemoveField(
            model_name='jornada',
            name='total_gasto_jornada',
        ),
        migrations.AlterField(
            model_name='jornada',
            name='cobro_tarea_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='cobro_tarea_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='gasto_extra_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='gasto_extra_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='gasto_extra_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(18, 13, 25, 419496), editable=False),
        ),
        migrations.AlterField(
            model_name='jornadaportrato',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(18, 13, 25, 420494), editable=False),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(18, 13, 25, 417502), editable=False),
        ),
    ]
