# Generated by Django 4.2.3 on 2024-09-25 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0005_remove_jornada_detalle_gasto_total_tareas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornada',
            name='es_jornada_por_trato',
        ),
        migrations.AddField(
            model_name='jornada',
            name='detalle_gasto_total_tareas',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='jornada',
            name='detalle_gastos_total_extras',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='jornada',
            name='total_gasto_jornada',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='cobro_tarea_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='cobro_tarea_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='gasto_extra_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='gasto_extra_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='gasto_extra_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(19, 31, 25, 160978), editable=False),
        ),
        migrations.AlterField(
            model_name='jornadaportrato',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(19, 31, 25, 161975), editable=False),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(19, 31, 25, 159981), editable=False),
        ),
    ]
