# Generated by Django 4.2.3 on 2024-09-25 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0006_remove_jornada_es_jornada_por_trato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='es_jornada_por_trato',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(19, 44, 58, 88359), editable=False),
        ),
        migrations.AlterField(
            model_name='jornadaportrato',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(19, 44, 58, 89356), editable=False),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(19, 44, 58, 87361), editable=False),
        ),
    ]
