# Generated by Django 5.2.5 on 2025-08-28 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0006_procesos_cantidad_procesos_ubicacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresario',
            name='tipo_cultivo',
        ),
        migrations.AlterField(
            model_name='jornada',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(16, 43, 21, 406567), editable=False),
        ),
        migrations.AlterField(
            model_name='jornadaportrato',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(16, 43, 21, 408578), editable=False),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(16, 43, 21, 404555), editable=False),
        ),
    ]
