# Generated by Django 4.2.3 on 2024-10-07 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0006_alter_jornada_hora_creacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finanzasportrabajador',
            options={},
        ),
        migrations.AlterField(
            model_name='jornada',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(17, 48, 35, 546552), editable=False),
        ),
        migrations.AlterField(
            model_name='jornadaportrato',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(17, 48, 35, 548553), editable=False),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(17, 48, 35, 545557), editable=False),
        ),
    ]
