# Generated by Django 4.2.3 on 2024-10-07 21:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0007_alter_finanzasportrabajador_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornada',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(18, 3, 21, 787138), editable=False),
        ),
        migrations.AlterField(
            model_name='jornadaportrato',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(18, 3, 21, 788151), editable=False),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(18, 3, 21, 785491), editable=False),
        ),
        migrations.CreateModel(
            name='FinanzasPorTrabajadorPorMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mes', models.DateField()),
                ('total_gasto_jornadas_horas', models.IntegerField(default=0, editable=False)),
                ('total_gasto_jornadas_trato', models.IntegerField(default=0, editable=False)),
                ('total_gasto_mes', models.IntegerField(default=0, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finanzas_creadas_pormes', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrosmartiotweb.trabajador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_mes'],
            },
        ),
    ]
