# Generated by Django 5.2.5 on 2025-08-28 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0007_remove_empresario_tipo_cultivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesos',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(17, 20, 34, 71666), editable=False),
        ),
        migrations.AlterField(
            model_name='jornadaportrato',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(17, 20, 34, 71666), editable=False),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(17, 20, 34, 71666), editable=False),
        ),
    ]
