# Generated by Django 5.2.5 on 2025-08-28 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0008_procesos_total_alter_jornada_hora_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='huerto',
            name='coordenadas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(17, 51, 50, 257848), editable=False),
        ),
        migrations.AlterField(
            model_name='jornadaportrato',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(17, 51, 50, 259848), editable=False),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(17, 51, 50, 256848), editable=False),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
