# Generated by Django 5.2.5 on 2026-08-24 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosmartiotweb', '0015_alter_jornada_hora_creacion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empresario',
            new_name='Empresario_Proveedor',
        ),
        migrations.AlterField(
            model_name='jornada',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(0, 2, 15, 507900), editable=False),
        ),
        migrations.AlterField(
            model_name='jornadaportrato',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(0, 2, 15, 531273), editable=False),
        ),
        migrations.AlterField(
            model_name='jornadaportrato',
            name='nombre_tarea_1',
            field=models.CharField(choices=[('PODA', 'Poda'), ('DESHOJE', 'Deshoje (sacar hojas)'), ('DESBROTE', 'Desbrote'), ('PESTICIDAS', 'Aplicación de pesticidas'), ('FERTILIZANTES', 'Aplicación de fertilizantes'), ('COSECHA', 'Cosecha'), ('AMARRE_GUIAS', 'Amarre de guías'), ('LIMPIEZA_MALEZA', 'Limpieza de maleza'), ('RIEGO', 'Riego'), ('PREPARACION_SUELO', 'Preparación del suelo'), ('PLANTACION', 'Plantación de cultivos'), ('ABONADO', 'Abonado'), ('LABRANZA', 'Labranza'), ('CONTROL_PLAGAS', 'Control manual de plagas'), ('DESINFECCION_SUELOS', 'Desinfección de suelos'), ('MONITOREO_CULTIVOS', 'Monitoreo de cultivos'), ('INSTALACION_RIEGO', 'Instalación de sistemas de riego'), ('RECOLECCION_RESIDUOS', 'Recolección de residuos'), ('INSTALACION_TUTORES', 'Instalación de tutores'), ('PODA_FORMACION', 'Poda de formación'), ('PODA_MANTENIMIENTO', 'Poda de mantenimiento'), ('ENTRESACADO_FRUTOS', 'Entresacado de frutos'), ('REPARACION_CERCAS', 'Reparación de cercas'), ('INSTALACION_RED_PROTECCION', 'Instalación de redes de protección'), ('MANEJO_POST_COSECHA', 'Manejo post-cosecha'), ('CLASIFICACION_UVAS', 'Clasificación de uvas'), ('TRANSPORTE_CARGA', 'Transporte de carga'), ('MANTENIMIENTO_MAQUINARIA', 'Mantenimiento de maquinaria'), ('REPLANTE_PLANTAS', 'Replante de plantas'), ('ACARREO_INSUMOS', 'Acarreo de insumos'), ('MANTENIMIENTO_RIEGO', 'Mantenimiento de sistemas de riego'), ('CONTROL_EROSION', 'Control de erosión'), ('CUBIERTA_ORGANICA', 'Colocación de cubierta orgánica'), ('APLICACION_BIOESTIMULANTES', 'Aplicación de bioestimulantes'), ('FERTIRRIGACION', 'Fertirrigación'), ('INSTALACION_SOMBREADO', 'Instalación de sistemas de sombreado'), ('DESINFECCION_HERRAMIENTAS', 'Desinfección de herramientas'), ('CAPACITACION_PERSONAL', 'Capacitación del personal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='jornadaportrato',
            name='nombre_tarea_2',
            field=models.CharField(blank=True, choices=[('PODA', 'Poda'), ('DESHOJE', 'Deshoje (sacar hojas)'), ('DESBROTE', 'Desbrote'), ('PESTICIDAS', 'Aplicación de pesticidas'), ('FERTILIZANTES', 'Aplicación de fertilizantes'), ('COSECHA', 'Cosecha'), ('AMARRE_GUIAS', 'Amarre de guías'), ('LIMPIEZA_MALEZA', 'Limpieza de maleza'), ('RIEGO', 'Riego'), ('PREPARACION_SUELO', 'Preparación del suelo'), ('PLANTACION', 'Plantación de cultivos'), ('ABONADO', 'Abonado'), ('LABRANZA', 'Labranza'), ('CONTROL_PLAGAS', 'Control manual de plagas'), ('DESINFECCION_SUELOS', 'Desinfección de suelos'), ('MONITOREO_CULTIVOS', 'Monitoreo de cultivos'), ('INSTALACION_RIEGO', 'Instalación de sistemas de riego'), ('RECOLECCION_RESIDUOS', 'Recolección de residuos'), ('INSTALACION_TUTORES', 'Instalación de tutores'), ('PODA_FORMACION', 'Poda de formación'), ('PODA_MANTENIMIENTO', 'Poda de mantenimiento'), ('ENTRESACADO_FRUTOS', 'Entresacado de frutos'), ('REPARACION_CERCAS', 'Reparación de cercas'), ('INSTALACION_RED_PROTECCION', 'Instalación de redes de protección'), ('MANEJO_POST_COSECHA', 'Manejo post-cosecha'), ('CLASIFICACION_UVAS', 'Clasificación de uvas'), ('TRANSPORTE_CARGA', 'Transporte de carga'), ('MANTENIMIENTO_MAQUINARIA', 'Mantenimiento de maquinaria'), ('REPLANTE_PLANTAS', 'Replante de plantas'), ('ACARREO_INSUMOS', 'Acarreo de insumos'), ('MANTENIMIENTO_RIEGO', 'Mantenimiento de sistemas de riego'), ('CONTROL_EROSION', 'Control de erosión'), ('CUBIERTA_ORGANICA', 'Colocación de cubierta orgánica'), ('APLICACION_BIOESTIMULANTES', 'Aplicación de bioestimulantes'), ('FERTIRRIGACION', 'Fertirrigación'), ('INSTALACION_SOMBREADO', 'Instalación de sistemas de sombreado'), ('DESINFECCION_HERRAMIENTAS', 'Desinfección de herramientas'), ('CAPACITACION_PERSONAL', 'Capacitación del personal')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jornadaportrato',
            name='nombre_tarea_3',
            field=models.CharField(blank=True, choices=[('PODA', 'Poda'), ('DESHOJE', 'Deshoje (sacar hojas)'), ('DESBROTE', 'Desbrote'), ('PESTICIDAS', 'Aplicación de pesticidas'), ('FERTILIZANTES', 'Aplicación de fertilizantes'), ('COSECHA', 'Cosecha'), ('AMARRE_GUIAS', 'Amarre de guías'), ('LIMPIEZA_MALEZA', 'Limpieza de maleza'), ('RIEGO', 'Riego'), ('PREPARACION_SUELO', 'Preparación del suelo'), ('PLANTACION', 'Plantación de cultivos'), ('ABONADO', 'Abonado'), ('LABRANZA', 'Labranza'), ('CONTROL_PLAGAS', 'Control manual de plagas'), ('DESINFECCION_SUELOS', 'Desinfección de suelos'), ('MONITOREO_CULTIVOS', 'Monitoreo de cultivos'), ('INSTALACION_RIEGO', 'Instalación de sistemas de riego'), ('RECOLECCION_RESIDUOS', 'Recolección de residuos'), ('INSTALACION_TUTORES', 'Instalación de tutores'), ('PODA_FORMACION', 'Poda de formación'), ('PODA_MANTENIMIENTO', 'Poda de mantenimiento'), ('ENTRESACADO_FRUTOS', 'Entresacado de frutos'), ('REPARACION_CERCAS', 'Reparación de cercas'), ('INSTALACION_RED_PROTECCION', 'Instalación de redes de protección'), ('MANEJO_POST_COSECHA', 'Manejo post-cosecha'), ('CLASIFICACION_UVAS', 'Clasificación de uvas'), ('TRANSPORTE_CARGA', 'Transporte de carga'), ('MANTENIMIENTO_MAQUINARIA', 'Mantenimiento de maquinaria'), ('REPLANTE_PLANTAS', 'Replante de plantas'), ('ACARREO_INSUMOS', 'Acarreo de insumos'), ('MANTENIMIENTO_RIEGO', 'Mantenimiento de sistemas de riego'), ('CONTROL_EROSION', 'Control de erosión'), ('CUBIERTA_ORGANICA', 'Colocación de cubierta orgánica'), ('APLICACION_BIOESTIMULANTES', 'Aplicación de bioestimulantes'), ('FERTIRRIGACION', 'Fertirrigación'), ('INSTALACION_SOMBREADO', 'Instalación de sistemas de sombreado'), ('DESINFECCION_HERRAMIENTAS', 'Desinfección de herramientas'), ('CAPACITACION_PERSONAL', 'Capacitación del personal')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='hora_creacion',
            field=models.TimeField(default=datetime.time(0, 2, 15, 507900), editable=False),
        ),
    ]
