"""
Django settings for agrosmartiot project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path
#import django_heroku
#import pytz
from django.contrib.messages import constants as message_constants
AUTH_USER_MODEL = 'agrosmartiotweb.CustomUser'
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i+h^ifkudr)+q*__he#@n=#=q*rk17-b!3^ns4vmt+5og7sqz1'


# SECURITY WARNING: don't run with debug turned on in production!
from decouple import config as _config_debug
DEBUG = _config_debug('DEBUG', default=False, cast=bool)
# settings.py

LOGIN_FORM = 'agrosmartiotweb.forms.CustomLoginForm'
LOGIN_URL = 'login'
MESSAGE_STORAGE = "django.contrib.messages.storage.cookie.CookieStorage"

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

import decouple

from decouple import config

ANTHROPIC_API_KEY = config('ANTHROPIC_API_KEY')
# Application definition
OPENWEATHER_API_KEY = config('OPENWEATHER_API_KEY')
INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     'agrosmartiot','chatbot',   # ← agregar aquí
    'django.contrib.humanize', 'crispy_forms', "django_filters", "rest_framework", "import_export", "mptt","channels","bootstrap4",
    'crispy_bootstrap4','agrosmartiotweb.apps.AgrosmartConfig',  # Asegúrate de que esta línea esté presente
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"

CRISPY_TEMPLATE_PACK = 'bootstrap4'
WSGI_APPLICATION = 'agrosmartiot.wsgi.application'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'agrosmartiotweb.middleware.LoginRequiredMiddleware',
]

# Rutas accesibles sin sesión iniciada. Todo lo demás exige login
# (ver agrosmartiotweb/middleware.py -> LoginRequiredMiddleware).
LOGIN_EXEMPT_URL_NAMES = {
    'home',
    'login', 'my_login', 'password_reset', 'password_reset_done',
    'password_reset_confirm', 'password_reset_complete',
    'firebase-sw',
    # Endpoints que llaman los dispositivos/sensores IoT, no navegadores logueados:
    'receive_data', 'receive_data_soil', 'device_status_api',
}
LOGIN_EXEMPT_PATH_PREFIXES = ('/admin/', '/static/', '/media/')

ROOT_URLCONF = 'agrosmartiot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates/agrosmart'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'agrosmartiotweb.context_processors.notificaciones_context',
                'agrosmartiotweb.context_processors.vapid_key',   # <-- nuevo
                'agrosmartiotweb.context_processors.empresa_info',

                
            ],
        },
    },
]


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

#import dj_database_url
#import os

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),  # Ubicación del archivo de la base de datos
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'd6vjp9pblsa0c2',
        'USER': 'u59j640n334lri',
        'PASSWORD': 'p24b71f9a41726e50706096b53f39f27348007d0f1056c4a22d7ca1a931a746dc',
        'HOST': 'cet8r1hlj0mlnt.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com',
        'PORT': '5432',
    }
}


# settings.py
AUTHENTICATION_BACKENDS = [
    'agrosmartiotweb.authentication.CaseInsensitiveModelBackend',
    'django.contrib.auth.backends.ModelBackend',

]

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/
LANGUAGE_CODE = 'es'
TIME_ZONE = 'America/Santiago'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
MESSAGE_LEVEL = message_constants.DEBUG
# Kafka
#KAFKA_SERVER = 'localhost:9092'
#KAFKA_TOPIC = 'temperatura-topic'

# Django Heroku settings

SESSION_COOKIE_SECURE = False  # Si no estás usando HTTPS, asegúrate de que esto sea False
CSRF_COOKIE_SECURE = False     # Asegúrate de que sea False en desarrollo
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

ALLOWED_HOSTS = [
    'smartagro-iot-v1-b4536d10714e.herokuapp.com',
    '.herokuapp.com',
    'smartagroiot.com',
    'www.smartagroiot.com',
    '127.0.0.1',
    'localhost',
]

CSRF_TRUSTED_ORIGINS = [
    'https://smartagro-iot-v1-b4536d10714e.herokuapp.com',
    'https://smartagroiot.com',
    'https://www.smartagroiot.com',
]
#import os

import ssl
import os
# settings.py
import os

WEBPUSH_SETTINGS = {
    'VAPID_PUBLIC_KEY': os.environ.get('VAPID_PUBLIC_KEY'),
}

REDIS_URL = os.environ.get("REDIS_TLS_URL") or os.environ.get("REDIS_URL")

if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [{
                    "address": REDIS_URL,
                    "ssl": {
                        "cert_reqs": ssl.CERT_NONE,
                    },
                }],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }
ASGI_APPLICATION = 'agrosmartiot.asgi.application'